# -*- coding: utf-8 -*-
"""arrays.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1L3MTiP4NK-tChrQk55g0wSfcewX9gagv
"""

# Importing numpy to work with arrays

import numpy as np

# Unidimensional array

v1 = array([1,2,3,4,5,6,7,8,9,10])
v1

# Multidimensional array

m1 = array([[1,2],[3,4],[5,6]])
m1