# -*- coding: utf-8 -*-
"""if-else.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zMed6K7Jqsd2-5c7kkJ9bO78Q8N7yHZp
"""

# Simple If

a = int(input("Value A: "))
b = int(input("Value B: "))

if a > b:
    print ("'A' is bigger!")
if b > a:
    print ("'B' is bigger!")

# If - Else

a = int(input("Value A: "))
b = int(input("Value B: "))

if a > b:
    print ("'A' is bigger!")
else:
    print ("'B' is bigger!")

# Double If - Else

a = int(input("Value A: "))
b = int(input("Value B: "))

if a > b:
    print ("'A' is bigger!")
if b > a:
    print ("'B' is bigger!")
else:
    print ("The values are the same!")

#Exercicio If - Else If - Else

a = int(input("Value A: "))
b = int(input("Value B: "))

if a > b:
    print ("'A' is bigger!")
elif b > a:
    print ("'B' is bigger!")
else:
    print ("The values are the same!")