# -*- coding: utf-8 -*-
"""imports.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1G_Ln-Tph8vmDsTSDGvG_ys-5SgYywt45
"""

# Import all lib

from numpy import*

# Imports just a specific part of the lib and names it

from numpy import random as rr

# Imports the lib only in function

import numpy as np

np.random.rand(1)